package lithium.openstud.driver.core.models;

public enum CertificateType {
    REGISTRATION, EXAMS_COMPLETED,GRADUATION_WITH_EXAMS, GRADUATION_WITH_GRADE, GRADUATION_WITH_THESIS, GRADUATION_FOR_RANSOM,
    GRADUATION_WITH_THESIS_ENG, GRADUATION_WITH_EXAMS_ENG, GRADUATION_WITH_GRADE_ENG
}
